version: '3.7'

services:
  database_silva:
    image: postgres
    container_name: database_silva
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rent
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: rent
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
